"""Authentication endpoints, ported from the Xano `scripters` API group."""
from datetime import UTC, datetime, timedelta

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select

from app.core.deps import current_user
from app.core.errors import XanoError
from app.core.security import create_access_token, hash_password, verify_password
from app.database import get_session
from app.models import User
from app.schemas.auth import (
    LoginIn,
    PasswordlessIn,
    PasswordlessResponse,
    SignupIn,
    TokenResponse,
)
from app.schemas.otp import (
    MessageResponse,
    StoreOtpIn,
    StoreOtpResponse,
    UpdatePasswordIn,
    VerifyOtpIn,
)
from app.schemas.user import UserMe
from app.services.accounts import (
    claim_purchases_made_before_signup,
    create_default_child,
    create_user,
    refuse_if_email_taken,
)

router = APIRouter(tags=["auth"])

# Xano writes null into NOT NULL timestamp columns; what lands is the epoch.
EPOCH = datetime(1970, 1, 1, tzinfo=UTC)


@router.get("/auth/me", response_model=UserMe)
async def auth_me(user: User = Depends(current_user)) -> User:
    """The signed-in user's own record.

    Ported from .../54_auth_me.xs. Xano projects the row to eight columns; the
    response model enforces the same list, so nothing extra leaks.
    """
    return user


@router.post("/auth/login", response_model=TokenResponse)
async def auth_login(
    body: LoginIn,
    db: AsyncSession = Depends(get_session),
) -> TokenResponse:
    """Exchange email and password for a token.

    Ported from .../53_auth_login.xs. Both preconditions there use the same
    message — a missing account and a wrong password are deliberately
    indistinguishable, so account existence cannot be probed. Kept that way.

    See xano-export/parity-questions.md #1: Xano's preconditions here carry no
    error_type, so the exact status is unconfirmed. 401 is assumed.
    """
    user = (await db.execute(
        select(User).where(User.email == body.email))).scalar_one_or_none()

    if user is None or not user.password:
        raise XanoError("unauthorized", "Invalid Credentials.")
    if not body.password or not verify_password(body.password, user.password):
        raise XanoError("unauthorized", "Invalid Credentials.")

    return TokenResponse(authToken=create_access_token(user.id))


@router.post("/auth/signup", response_model=TokenResponse)
async def auth_signup(
    body: SignupIn,
    db: AsyncSession = Depends(get_session),
) -> TokenResponse:
    """Create an account, its placeholder child, and adopt earlier purchases.

    Ported from .../52_auth_signup.xs.
    """
    await refuse_if_email_taken(db, body.email)

    user = await create_user(
        db, name=body.name, email=body.email,
        password_hash=hash_password(body.password) if body.password else None)
    child = await create_default_child(db, user)
    await claim_purchases_made_before_signup(db, user, child, body.email)
    await db.commit()

    return TokenResponse(authToken=create_access_token(user.id))


@router.post("/register_passwordless", response_model=PasswordlessResponse)
async def register_passwordless(
    body: PasswordlessIn,
    db: AsyncSession = Depends(get_session),
) -> PasswordlessResponse:
    """Create an account with no password at all.

    Ported from .../73_register_passwordless.xs. Note what it does *not* do,
    unlike auth/signup: no placeholder child, and no adoption of earlier
    purchases. The signup flow calls this one.
    """
    await refuse_if_email_taken(db, body.email)

    user = await create_user(db, name=body.name, email=body.email)
    await db.commit()

    return PasswordlessResponse(
        message="user created successfully",
        authToken=create_access_token(user.id))


@router.post("/otp/store", response_model=StoreOtpResponse)
async def store_otp(
    body: StoreOtpIn,
    db: AsyncSession = Depends(get_session),
) -> StoreOtpResponse:
    """Record an externally generated OTP against a user.

    Ported from .../63_otp_store.xs. The code itself is generated by the Next.js
    route (app/api/auth/forgot-password); this endpoint only stores it and its
    expiry, computed as now + expiresIn seconds.
    """
    user = (await db.execute(
        select(User).where(User.email == body.email))).scalar_one_or_none()
    if user is None:
        raise XanoError("inputerror", "User not found")

    user.otp = body.otp
    user.otp_expiry = datetime.now(UTC) + timedelta(seconds=body.expiresIn)
    db.add(user)
    await db.commit()

    return StoreOtpResponse(success=True, message="OTP stored successfully")


@router.post("/verify_otp", response_model=MessageResponse)
async def verify_otp(
    body: VerifyOtpIn,
    db: AsyncSession = Depends(get_session),
) -> MessageResponse:
    """Check a one-time code and burn it.

    Ported from .../64_verify_otp.xs. Xano writes null into `otp` and
    `otp_expiry` afterwards, but both columns are NOT NULL, so what actually
    lands is each type's zero value — "" and the epoch. Reproduced, which also
    keeps a replayed empty code from passing: the expiry check fails first.
    """
    user = (await db.execute(
        select(User).where(User.email == body.email))).scalar_one_or_none()
    if user is None:
        raise XanoError("inputerror", "User not found.")
    if body.otp != user.otp:
        raise XanoError("inputerror", "Invalid OTP code. Please try again.")
    if user.otp_expiry is None or datetime.now(UTC) > user.otp_expiry:
        raise XanoError("inputerror", "OTP has expired. Please request a new one.")

    user.otp = ""
    user.otp_expiry = EPOCH
    db.add(user)
    await db.commit()

    return MessageResponse(message="OTP verified successfully")


@router.post("/update_password", response_model=MessageResponse)
async def update_password(
    body: UpdatePasswordIn,
    db: AsyncSession = Depends(get_session),
) -> MessageResponse:
    """Set a new password for the account with this email address.

    Ported from .../65_update_password.xs.

    SECURITY, reproduced deliberately under the auth-parity rule: this endpoint
    takes an email and a new password and nothing else. It has no auth, and it
    does not check that verify_otp ever succeeded — there is no token, flag or
    timestamp linking the two. Anyone who knows an address can take the account.
    Xano behaves the same way today. Flagged for triage; not changed here,
    because changing it would break the parity diff and hide the fact.
    """
    user = (await db.execute(
        select(User).where(User.email == body.email))).scalar_one_or_none()
    if user is None:
        raise XanoError("accessdenied", "404 Not Found")

    user.password = hash_password(body.newPassword)
    db.add(user)
    await db.commit()

    return MessageResponse(message="Password updated successfully")
