"""initial schema from xano

Revision ID: b7ed310e58da
Revises: 
Create Date: 2026-08-24 18:09:16.859691
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated migrations
from sqlalchemy.dialects import postgresql

revision: str = 'b7ed310e58da'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_01_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('time_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lat', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('lon', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('pronoun', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_child', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('relationship_focus', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'child'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_01_id', 'name', 'date_of_birth', name='uq_children_user_01_id_name_date_of_birth')
    )
    op.create_index('ix_children_created_at', 'children', ['created_at'], unique=False)
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('html_content', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text("'epoch'"), nullable=False),
    sa.Column('delivered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_created_at', 'email', ['created_at'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('real_user_id', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('deep_text', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('summary_text', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('teaser_text', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('insights_api_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insights_created_at', 'insights', ['created_at'], unique=False)
    op.create_table('journey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('number', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journey_created_at', 'journey', ['created_at'], unique=False)
    op.create_table('onboarding_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("'epoch'"), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('flow', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('step', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('step_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'flow', 'step', name='uq_onboarding_visit_session_id_flow_step')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Uuid(), nullable=True),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_source', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('purchase_reference', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchases_created_at', 'purchases', ['created_at'], unique=False)
    op.create_table('user_01',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('memberstack_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('time_of_birth', sa.DateTime(timezone=True), server_default=sa.text("'epoch'"), nullable=False),
    sa.Column('lat', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('lon', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('pronoun', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_01_email'),
    sa.UniqueConstraint('memberstack_id', name='uq_user_01_memberstack_id')
    )
    op.create_index('ix_user_01_created_at', 'user_01', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_id', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('password_reset', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('otp', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.Column('otp_expiry', sa.DateTime(timezone=True), server_default=sa.text("'epoch'"), nullable=False),
    sa.Column('relationship_focus', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_user_01_created_at', table_name='user_01')
    op.drop_table('user_01')
    op.drop_index('ix_purchases_created_at', table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('onboarding_visit')
    op.drop_index('ix_journey_created_at', table_name='journey')
    op.drop_table('journey')
    op.drop_index('ix_insights_created_at', table_name='insights')
    op.drop_table('insights')
    op.drop_index('ix_email_created_at', table_name='email')
    op.drop_table('email')
    op.drop_index('ix_children_created_at', table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###
