// Stroes the relation we generate based on the parent and his/her child details
table Insights {
  auth = false

  schema {
    uuid id
    timestamp created_at?=now {
      visibility = "private"
    }
  
    int real_user_id? {
      table = "user"
    }
  
    // References the children table for the child associated with the insight.
    uuid child_id? {
      table = "children"
    }
  
    // References the Journey table for the journey associated with the insight.
    uuid journey_id? {
      table = "Journey"
    }
  
    // Stores the status of the insights records
    enum status? {
      values = ["processing", "ready", "failed"]
    }
  
    text deep_text? filters=trim
    text summary_text? filters=trim
  
    // To store the teaser generated by Cloude AI Service
    text teaser_text? filters=trim
  
    // Identifier for the request that generated the insight.
    uuid request_id?
  
    // Stores the last error message if insight processing fails.
    text last_error? filters=trim
  
    // Stores the JSON input used to generate the insight.
    json insights_api_payload?
  }

  index = [
    {type: "primary", field: [{name: "id"}]}
    {type: "btree", field: [{name: "created_at", op: "desc"}]}
  ]
}